from django.test import TestCase

# Create your tests here.


json_data_1 = {"Title": "The Equation c=mv^2", "Sections": [{"SectionTitle": "Introduction", "SectionContent": "The equation c=mv^2 is a fundamental equation in physics that relates the momentum, mass, and velocity of an object. It is commonly known as the kinetic energy equation."}, {"SectionTitle": "Understanding the Equation", "SectionContent": "In this equation, 'c' represents the kinetic energy of an object, 'm' represents its mass, and 'v' represents its velocity. The equation states that the kinetic energy of an object is equal to its mass multiplied by the square of its velocity."}, {"SectionTitle": "Significance", "SectionContent": "The equation c=mv^2 helps us understand the relationship between an object's mass, velocity, and energy. It demonstrates that the kinetic energy of an object increases quadratically with its velocity. This means that even a small increase in speed can result in a significant increase in kinetic energy."}, {"SectionTitle": "Application", "SectionContent": "The equation c=mv^2 is used in various fields of physics, including mechanics, thermodynamics, and kinematics. It allows us to calculate the kinetic energy of objects in motion, predict the behavior of moving systems, and analyze the efficiency of mechanical processes."}, {"SectionTitle": "Conclusion", "SectionContent": "The equation c=mv^2 is a fundamental tool in physics that relates the kinetic energy of an object to its mass and velocity. Understanding this equation helps us comprehend the relationship between these variables and apply it to various physical phenomena."}]}



json_data_2 = {"Title": "Graph", "Sections": [{"SectionTitle": "Introduction", "SectionContent": "A graph is a way to represent and analyze relationships or connections between different entities, such as people, places, or concepts. It consists of a set of nodes or vertices, which represent the entities, and a set of edges or links, which represent the relationships between the entities."}, {"SectionTitle": "Types of Graphs", "SectionContent": "There are various types of graphs, including directed graphs, undirected graphs, weighted graphs, and bipartite graphs.\n\n- In a directed graph, the edges have a specific direction, indicating the flow of the relationship.\n- In an undirected graph, the edges have no direction, representing a symmetric relationship.\n- A weighted graph assigns a value or weight to each edge, indicating the strength or cost of the relationship.\n- Bipartite graphs have two sets of nodes, with edges only connecting nodes from different sets."}, {"SectionTitle": "Common Uses", "SectionContent": "Graphs are widely used in various fields:\n\n- Social networks: Graphs can represent relationships between individuals in social networks, helping analyze connections and patterns.\n- Transportation networks: Graphs can model road networks, flight connections, or subway systems, aiding in route optimization and planning.\n- Internet and web: Graphs can represent website links or online networks, supporting search algorithms and recommendation systems.\n- Computer science and algorithms: Graphs are essential for solving problems like shortest path finding, minimum spanning tree, or network flow calculations."}, {"SectionTitle": "Conclusion", "SectionContent": "Graphs provide a powerful way to visualize and analyze relationships between different entities. Understanding graphs and their various types and applications can greatly aid in solving real-world problems across many domains."}]}



# json_bad_data_1 = {'Title': 'What is Fortnite?', 'Sections': [ {'SectionTitle': 'Introduction', 'SectionContent': 'Fortnite is a popular online video game that was developed by Epic Games. It was first released in 2017 and has gained a massive following since then. The game is available on various platforms including PC, consoles, and mobile devices.'}, {'SectionTitle': 'Gameplay', 'SectionContent': 'Fortnite is a battle royale game where players are dropped onto a virtual island and must fight to be the last person standing. The game features a unique building mechanic where players can gather resources and construct structures for defense or to gain an advantage over their opponents. In addition to the battle royale mode, Fortnite also offers other game modes such as Creative and Save the World.'}, {'SectionTitle':'Conclusion', 'SectionContent': 'Fortnite has become a cultural phenomenon, attracting millions of players worldwide. It is known for its vibrant graphics, fast-paced gameplay, and constant updates that introduce new content and features. Whether you're a casual gamer or a competitive player, Fortnite offers a fun and exciting gaming experience.'}]}

